Cargo.lock
Cargo.toml
src/main.rs

Upgrade tokio version to 1.5
Fixes #
Ref #

chore: upgrade tokio version to 1.5

---

devtools/config/config.toml
src/config.rs
src/extensions/mod.rs
src/extensions/tests/mod.rs
src/extensions/udt_balance/mod.rs
src/extensions/udt_balance/types.rs
src/rpc/mod.rs
src/rpc/rpc_impl.rs

Add xUDT balance indexer and RPC interface.
Fixes #
Ref #

feat(udt): add xUDT balance indexer and RPC interface

---

.github/workflows/ci.yml
.github/workflows/code_lint.yml

Make code lint check stand alone
Fixes #
Ref #

ci: make code lint checks stand alone

---

Cargo.lock
Cargo.toml
devtools/config/config.toml
src/cli.rs
src/config.rs
src/main.rs
src/service.rs

Add mercury cli and snapshot.
Fixes #
Ref #

feat(cli): add mercury cli and snapshot

---

Cargo.lock
Cargo.toml
clippy.toml
src/cli.rs
src/config.rs
src/extensions/anyone_can_pay/mod.rs
src/extensions/anyone_can_pay/types.rs
src/extensions/ckb_balance/types.rs
src/extensions/lock_time/mod.rs
src/extensions/lock_time/types.rs
src/extensions/mod.rs
src/extensions/tests/mod.rs
src/service.rs
src/stores.rs
src/utils.rs

feat(extension): add lock time and anyone can pay extension

---

devtools/config/config.toml

refactor(config): change the config file

---

Cargo.lock
devtools/config/config.toml
src/extensions/lock_time/mod.rs
src/extensions/mod.rs
src/extensions/special_cells/mod.rs
src/extensions/special_cells/types.rs
src/extensions/tests/mod.rs

1. Rename acp extension to special cells extension
2. Refactor the data structure of special cells extension. Change saving detailed cell instead of the cell out point.
3. Add cheque cell indexer to special cells extension
Fixes #
Ref #

feat(ext): refactor and add cheque to special cells extension

---

.gitignore
src/extensions/udt_balance/mod.rs
src/service.rs

fix: overflow when change maturity threshold

---

src/rpc/mod.rs
src/rpc/rpc_impl.rs
src/rpc/rpc_impl/transfer.rs
src/rpc/tests/mod.rs
src/rpc/tests/transfer_completion.rs
src/rpc/types.rs

refactor(rpc): rename address to ident and rpc interface

---

README.md

docs: add install and run document

---

README.md

docs: rename README

---

devtools/config/config.toml
src/extensions/udt_balance/mod.rs
src/rpc/rpc_impl/transfer.rs
src/rpc/tests/transfer_completion.rs
src/rpc/types.rs

feat(rpc): add group signatures len in response

---

devtools/config/mainnet_config.toml
devtools/config/testnet_config.toml
src/rpc/rpc_impl/transfer.rs
src/rpc/tests/mod.rs
src/rpc/tests/transfer_completion.rs

refactor(rpc): change the fee unit from ckb to shannon

---

Cargo.lock

chore: cargo update ckb-indexer

---

Cargo.lock
Cargo.toml
src/rpc/mod.rs
src/rpc/rpc_impl.rs
src/rpc/rpc_impl/transfer.rs
src/service.rs

feat(rpc): add tx pool cache to filter input cells

---

src/rpc/tests/mod.rs
src/rpc/tests/transfer_completion.rs

fix: test db

---

.github/release-drafter.yml
.github/release_template.yml
.github/workflows/release.yml

chore(ci): add release version script

---

.github/release-drafter.yml
.github/workflows/pr_lint.yml

chore(ci): add PR kind labeler action

---

devtools/config/testnet_config.toml
src/extensions/ckb_balance/mod.rs
src/rpc/rpc_impl/query.rs

fix: calc cellbase capacity in ckb balance extension

---

README.md
devtools/config/testnet_config.toml
src/rpc/rpc_impl/query.rs

docs: change config file path in README

---

src/rpc/rpc_impl/transfer.rs

fix: cheque cell store bug

---

src/rpc/rpc_impl.rs
src/rpc/rpc_impl/transfer.rs
src/rpc/types.rs

feat: create acp for receiver when action is pay_by_from in udt transfer

---

core/extensions/src/ckb_balance/mod.rs
core/extensions/src/ckb_balance/types.rs
core/extensions/src/lib.rs
core/extensions/src/lock_time/mod.rs
core/extensions/src/lock_time/types.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/tests/mod.rs
core/rpc/src/tests/query_test.rs
core/rpc/src/types.rs
devtools/config/mainnet_config.toml
devtools/config/testnet_config.toml

refactor: get balance rpc interface and locktime extension

---

core/extensions/src/lock_time/mod.rs

fix: use filter instead of skip while in iterator

---

core/extensions/src/lock_time/mod.rs

fix: get others miner cellbase account iterator

---

Cargo.lock
core/rpc/Cargo.toml
core/rpc/src/error.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/tests/query_test.rs

feat(rpc): add get transaction history interface

---

.github/workflows/code_lint.yml
.github/workflows/pr_lint.yml
.github/workflows/release.yml

ci(release): add auto compile and upload binaries

---

Cargo.lock
core/rpc/Cargo.toml
core/rpc/src/error.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/types.rs
core/service/src/lib.rs

feat(rpc): add query charge block interface

---

Cargo.lock
Cargo.toml
common/Cargo.toml
common/src/address.rs
common/src/lib.rs
core/cli/Cargo.toml
core/cli/src/lib.rs
core/extensions/Cargo.toml
core/extensions/src/ckb_balance/mod.rs
core/extensions/src/lib.rs
core/extensions/src/lock_time/mod.rs
core/extensions/src/special_cells/mod.rs
core/rpc/Cargo.toml
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/transfer.rs
core/rpc/src/tests/mod.rs
core/rpc/src/tests/query_test.rs
core/rpc/src/tests/transfer_completion_test.rs
core/rpc/src/types.rs
core/service/src/lib.rs

feat(rpc): transfer completion support using claimable source

---

Cargo.lock
common/Cargo.toml
common/src/hash.rs
common/src/lib.rs
core/extensions/src/special_cells/mod.rs
core/rpc/src/error.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/transfer.rs
core/rpc/src/tests/mod.rs
core/rpc/src/tests/transfer_completion_test.rs
core/rpc/src/types.rs

refactor(rpc): change handle cheque process

---

Cargo.lock
devtools/config/mainnet_config.toml

chore(config): change cheque config in mainet into real

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/transfer.rs
core/rpc/src/tests/transfer_completion_test.rs
core/rpc/src/types.rs

feat(rpc): change an exact fee into fee rate when build transaction

---

Cargo.lock
core/extensions/src/special_cells/mod.rs

Remove the assertation of acp script args len.
Fixes #
Ref #

refactor: remove the assertation of acp script args len

---

core/rpc/src/rpc_impl/transfer.rs
core/rpc/src/tests/transfer_completion_test.rs

fix: calculate tx size missing offset

---

core/extensions/src/script_hash/mod.rs
core/extensions/src/script_hash/types.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/operation.rs
core/rpc/src/tests/mod.rs
core/rpc/src/tests/operation_test.rs

feat(extension): add index tx block number and hash extension

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/operation.rs
core/rpc/src/rpc_impl/transfer.rs
core/rpc/src/tests/mod.rs
core/rpc/src/tests/operation_test.rs
core/rpc/src/tests/query_test.rs
core/rpc/src/tests/transfer_completion_test.rs
core/rpc/src/types.rs

refactor(rpc): buid transfer transaction and wallet creation

---

Cargo.lock
core/rpc/Cargo.toml
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/operation.rs
core/rpc/src/rpc_impl/transfer.rs
core/service/src/lib.rs
devtools/config/testnet_config.toml

fix(rpc): cannot get cell by out point when it has been consumed

---

core/rpc/src/ckb_client.rs
core/rpc/src/rpc_impl.rs

refactor: return error when the ckb rpc return none

---

Cargo.lock
core/extensions/src/script_hash/mod.rs
core/extensions/src/script_hash/types.rs
core/rpc/Cargo.toml
core/rpc/src/error.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/types.rs
core/service/src/lib.rs

feat(rpc): query generic transaction

---

common/src/address.rs
common/src/lib.rs
common/src/utils.rs
core/extensions/src/special_cells/mod.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/operation.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/tests/mod.rs
core/rpc/src/tests/operation_test.rs

refactor: storage code hash of acp address payload

---

core/rpc/src/error.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/transfer.rs
core/rpc/src/tests/mod.rs
core/rpc/src/tests/transfer_completion_test.rs
core/rpc/src/types.rs

refactor(rpc): rename build_wallet_creation_transaction and build_transfer_transaction

---

core/rpc/src/rpc_impl/query.rs

fix(rpc): bug of query generic transactions

---

core/rpc/src/rpc_impl/query.rs

revert(rpc): revert query generic transaction

---

core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/operation.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/tests/mod.rs
core/rpc/src/tests/query_test.rs

fix(rpc): get tx hash by script from indexer

---

core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/transfer.rs
core/rpc/src/types.rs

fix(rpc): bug of sigs_entry of build_asset_collection_transaction

---

core/rpc/src/rpc_impl/transfer.rs

fix(rpc): bug of  sig_entry

---

core/extensions/src/script_hash/mod.rs
core/rpc/src/rpc_impl/transfer.rs
core/rpc/src/types.rs

fix(rpc): refactor sigs_entry and check cheque parse

---

core/service/src/lib.rs

refactor(service): add ckb indexer rpc impl

---

core/rpc/src/rpc_impl/transfer.rs

fix(rpc): update sigs_entry for each outpoint

---

core/rpc/src/rpc_impl/transfer.rs

fix(rpc): sig_entry of right index

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl/transfer.rs

fix(rpc): filter empty collection

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/transfer.rs

fix(rpc): insert output before drain

---

core/rpc/README.md
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs

feat(rpc): set default order of query_generic_transaction as desc

---

common/src/address.rs
core/extensions/src/tests/memory_store.rs
core/rpc/src/rpc_impl/operation.rs
core/rpc/src/tests/memory_db.rs
devtools/config/testnet_config.toml

refactor: parse acp address from lock script

---

README.md

docs: add refs of api

---

.github/workflows/release.yml
devtools/config/testnet_config.toml

ci: change the ubuntu version for create binary

---

core/rpc/README.md

docs: update rpc doc

---

core/rpc/README.md

docs: fix invalid ref 

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/transfer.rs

feat(rpc): filter empty balance and show details for AssetNotEnough Error

---

Cargo.lock
db/protocol/src/lib.rs
db/xsql/src/fetch.rs
db/xsql/src/lib.rs
db/xsql/src/table.rs

chore: cargo update and format rbatis proc macro

---

common/src/lib.rs
db/protocol/src/lib.rs
db/xsql/src/lib.rs

refactor(DB): change cursor type to i64 

---

db/xsql/src/insert.rs
db/xsql/src/lib.rs
db/xsql/src/table.rs
devtools/create_table/create_table.sql

refactor(DB): change some column from varchar to bytea

---

Cargo.lock
db/xsql/src/snowflake.rs
db/xsql/src/synchronize.rs
db/xsql/src/table.rs

feat(DB): sync canonical chain and change snowflake generator

---

db/xsql/src/insert.rs

fix(db): correct uncles_hash value when inserting.

---

Cargo.lock
common/src/utils.rs
db/protocol/src/lib.rs
db/xsql/Cargo.toml
db/xsql/src/error.rs
db/xsql/src/fetch.rs
db/xsql/src/lib.rs

feat(DB): impl db interface get_block_header

---

Cargo.lock
common/src/lib.rs
db/xsql/Cargo.toml
db/xsql/src/fetch.rs
db/xsql/src/insert.rs
db/xsql/src/lib.rs
db/xsql/src/sql.rs
db/xsql/src/synchronize.rs
db/xsql/src/table.rs

refactor(DB): change rbatis url that use bson instead of json

---

Cargo.lock
db/xsql/src/fetch.rs
db/xsql/src/insert.rs
db/xsql/src/synchronize.rs
db/xsql/src/table.rs

refactor(DB): change value uncles_hash to uncle_hashes 

---

Cargo.lock
db/xsql/src/error.rs
db/xsql/src/insert.rs
db/xsql/src/lib.rs
db/xsql/src/remove.rs
db/xsql/src/sql.rs

feat(DB): add rollback block process

---

db/xsql/src/fetch.rs

feat(DB): impl db interface get_block

---

Cargo.lock
common/src/lib.rs
db/protocol/src/lib.rs
db/xsql/src/fetch.rs
db/xsql/src/lib.rs
db/xsql/src/page.rs
db/xsql/src/remove.rs
db/xsql/src/table.rs

feat(DB): add cursor page plugin and query scripts

---

Cargo.lock
common/src/lib.rs
db/xsql/src/error.rs
db/xsql/src/fetch.rs
db/xsql/src/lib.rs

feat(DB): add query live cells interface

---

Cargo.lock
db/xsql/src/fetch.rs
db/xsql/src/page.rs

fix(DB): get order from page request instead of args

---

db/xsql/src/fetch.rs
db/xsql/src/lib.rs

feat(DB): impl get_transactions interface 

---

Cargo.lock
common/src/lib.rs
common/src/utils.rs
core/cli/Cargo.toml
core/cli/src/config.rs
core/extensions/Cargo.toml
core/rpc/Cargo.toml
core/rpc/src/ckb_client.rs
core/rpc/src/error.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/transfer.rs
core/rpc/src/tests/mod.rs
core/rpc/src/types.rs
core/service/Cargo.toml
core/service/src/lib.rs
core/storage/Cargo.toml
core/storage/src/lib.rs
devtools/config/mainnet_config.toml

test(rpc): add rpc unit test framework

---

common/src/lib.rs
core/rpc/src/ckb_client.rs
core/rpc/src/error.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/utils.rs
core/rpc/src/types.rs
core/storage/src/lib.rs
db/protocol/src/lib.rs
db/xsql/src/fetch.rs
db/xsql/src/lib.rs

feat(rpc): add some basic functions and tools

---

Cargo.lock
Cargo.toml
core/rpc/src/rpc_impl/utils.rs
core/storage/src/lib.rs
db/protocol/src/lib.rs
db/xsql/src/fetch.rs
db/xsql/src/lib.rs
db/xsql/src/tests/mod.rs
src/main.rs

feat(DB): add some new interfaces and abort when panic

---

Cargo.lock
Cargo.toml
common/src/utils.rs
core/rpc/src/error.rs
core/rpc/src/rpc_impl/utils.rs
core/rpc/src/tests/mod.rs
core/rpc/src/types.rs
core/service/src/lib.rs
core/storage/src/lib.rs
db/protocol/src/lib.rs
db/xsql/src/fetch.rs
db/xsql/src/lib.rs
db/xsql/src/synchronize.rs
db/xsql/src/tests/mod.rs
devtools/config/mainnet_config.toml
devtools/config/testnet_config.toml
src/main.rs

refactor(DB): get block from node in spawn task instead of main thread

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/utils.rs
core/rpc/src/tests/mod.rs
core/rpc/src/types.rs
core/service/src/lib.rs
core/storage/src/lib.rs
db/protocol/src/lib.rs
db/xsql/src/lib.rs
db/xsql/src/snowflake.rs
db/xsql/src/sql.rs

feat(rpc): add pool token and change asset type to strcut

---

Cargo.lock
core/cli/src/config.rs
core/cli/src/lib.rs
core/rpc/src/tests/mod.rs
core/service/Cargo.toml
core/service/src/lib.rs
core/storage/Cargo.toml
core/storage/src/lib.rs
db/xsql/src/lib.rs
db/xsql/src/synchronize.rs
db/xsql/src/tests/mod.rs
devtools/config/mainnet_config.toml
devtools/config/testnet_config.toml

feat(config): add need synchronization config

---

core/cli/src/config.rs
core/cli/src/lib.rs
db/xsql/src/table.rs
devtools/config/mainnet_config.toml
devtools/config/testnet_config.toml

refactor: change empty type script hash to H256 default

---

db/xsql-test/src/sql.rs
db/xsql/src/insert.rs
db/xsql/src/table.rs

refactor(DB): save batch tx cell and script in one block

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/utils.rs
core/rpc/src/types.rs
db/xsql/src/fetch.rs
db/xsql/src/sql.rs

refactror: fetch script count by sql wrapper

---

core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/types.rs
db/xsql-test/src/sql.rs
db/xsql/src/fetch.rs
db/xsql/src/insert.rs
db/xsql/src/sql.rs
db/xsql/src/table.rs
devtools/create_table/create_sqlite_table.sql
devtools/create_table/create_table.sql

refactor(DB): change since from bigint to bytea

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/utils.rs
core/storage/src/lib.rs
db/xsql/src/insert.rs

refactor(DB): append cells and scripts in block

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/utils.rs
core/rpc/src/types.rs
core/storage/src/lib.rs

feat: add build deposit transaction interface

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs
core/storage/src/lib.rs

feat(rpc): add get transaction info

---

.gitignore
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/consts.rs
core/rpc/src/rpc_impl/utils.rs
core/rpc/src/types.rs

feat: Modify return type of advance query

---

Cargo.lock
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/transfer.rs
core/rpc/src/tests/transfer_completion_test.rs
core/service/Cargo.toml

feat(rpc): add get account number interface

---

Cargo.lock
Cargo.toml
core/rpc/src/rpc_impl/operation.rs
core/rpc/src/types.rs
core/service/Cargo.toml

refactor(rpc): change asset status

---

Cargo.lock
core/rpc/src/rpc_impl/operation.rs
core/rpc/src/rpc_impl/query.rs

refactor: change the cheque key address in record

---

Cargo.lock
Cargo.toml
core/rpc/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml

chore: bump tokio version to 1.11

---

core/rpc/README.md
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/operation.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/types.rs

fix: get ckb locked balance and build record

---

Cargo.lock
core/rpc/Cargo.toml
core/service/Cargo.toml

chore: upgrade jsonrpsee version

---

core/storage/src/relational/fetch.rs
core/storage/src/relational/tests/mod.rs

fix: add cell base in get_transaction_views in storage.

---

core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/build_tx.rs

feat(rpc): impl build_deposit_tx

---

core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/utils.rs
core/rpc/src/types.rs

Fixes #
[Mercury JSON-RPC Protocols#query_transactions](https://github.com/nervosnetwork/mercury/blob/main/core/rpc/README.md#method-query_transactions)

feat(rpc): implement query_transactions

---

Cargo.lock
Cargo.toml
core/cli/src/config.rs
core/cli/src/lib.rs
core/rpc/src/rpc_impl/utils.rs
core/service/Cargo.toml
core/service/src/lib.rs
core/storage/Cargo.toml
core/storage/src/kvdb/mod.rs
core/storage/src/lib.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/insert.rs
core/storage/src/relational/mod.rs
core/storage/src/relational/remove.rs
core/storage/src/relational/table.rs
core/synchronization/Cargo.toml
core/synchronization/src/lib.rs
core/synchronization/src/sql.rs
core/synchronization/src/table.rs
db/protocol/src/lib.rs
db/rocksdb/Cargo.toml
db/rocksdb/src/lib.rs
db/xsql/src/lib.rs
devtools/config/mainnet_config.toml
devtools/config/testnet_config.toml
devtools/create_table/create_table.sql
src/main.rs

feat(sync): do synchronization in parallel

---

core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/utils.rs
core/synchronization/src/lib.rs

feat(rpc): check is in tx pool cache when pool cell

---

Cargo.lock
core/service/src/lib.rs
core/synchronization/Cargo.toml
core/synchronization/src/lib.rs
core/synchronization/src/sql.rs
core/synchronization/src/table.rs

fix(sync): fetch all exist script hash 

---

core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/query.rs

refactor(rpc): add inner methods

---

core/rpc/src/ckb_client.rs

refactor(rpc): multiple requests by a same connection

---

Cargo.lock
core/cli/src/lib.rs
core/storage/Cargo.toml
core/storage/src/relational/fetch.rs
core/storage/src/relational/insert.rs
core/storage/src/relational/mod.rs
core/storage/src/relational/remove.rs
core/storage/src/relational/sql.rs
core/storage/src/relational/table.rs

refactor(storage): change append block process

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/utils.rs

feat(rpc): add build withdraw transaction rpc interface

---

core/rpc/src/indexer_types.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs

feat(rpc): add type of indexer rpc API get_cells

---

common/src/lib.rs
core/rpc/README.md
core/rpc/src/indexer_types.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/utils.rs
core/rpc/src/tests/mod.rs
core/rpc/src/tests/query_test.rs
core/rpc/src/types.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs
db/xsql/src/page.rs

feat: adjust mercury interface

---

Makefile
core/storage/Cargo.toml
core/storage/src/kvdb/mod.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/insert.rs
core/storage/src/relational/table.rs
core/synchronization/src/lib.rs
db/rocksdb/Cargo.toml
db/rocksdb/src/lib.rs
db/xsql-test/src/lib.rs
db/xsql-test/src/sql.rs
devtools/create_table/create_sqlite_table.sql
devtools/create_table/create_table.sql

refactor(storage): remove uncle relationship table

---

core/rpc/src/indexer_types.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs

feat(rpc): implement indexer rpc api get_tip

---

core/rpc/src/indexer_types.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs

feat(rpc): implement indexer rpc api get_cells_capacity

---

Cargo.lock
Cargo.toml
core/inspection/Cargo.toml
core/inspection/src/lib.rs
core/rpc/src/tests/rpc_test.rs
core/storage/src/lib.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs
core/storage/src/relational/tests/get_cell_test.rs

feat(storage): add get cell from cell table interface

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/utils.rs
core/rpc/src/tests/mod.rs
core/rpc/src/tests/rpc_test.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs
core/storage/src/relational/sql.rs
core/synchronization/src/lib.rs
db/xsql/src/page.rs
devtools/test_data/blocks/100.json

fix(storage): fix some bugs in storage and rpc

---

core/storage/src/relational/tests/mod.rs
core/synchronization/src/lib.rs
core/synchronization/src/sql.rs

refactor(sync): change insert into mercury live cell process

---

core/synchronization/src/lib.rs
devtools/create_table/create_table.sql

feat(sql): add create index sql

---

core/rpc/src/rpc_impl/utils.rs
core/storage/src/relational/fetch.rs
devtools/config/mainnet_config.toml
devtools/config/testnet_config.toml

fix(rpc): fix some utils bug

---

Cargo.lock
core/synchronization/src/lib.rs
devtools/config/mainnet_config.toml

refactor(sync): free db transaction manually

---

Cargo.lock
core/rpc/Cargo.toml
core/rpc/src/types.rs
core/service/Cargo.toml

refactor(rpc): remove trimmed 0x of json item

---

core/rpc/src/rpc_impl.rs

refactor(rpc): swap init builtin scripts code hash

---

Cargo.lock
core/cli/Cargo.toml
core/cli/src/config.rs
core/cli/src/lib.rs
devtools/config/docker_compose_config.toml
devtools/config/mainnet_config.toml
devtools/config/testnet_config.toml

feat(cli): add indexer mode option

---

core/rpc/src/indexer_types.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs
core/storage/src/lib.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs
db/protocol/src/lib.rs

- feat(db): add DAO method to get consume info
- feat(rpc): implement indexer rpc api get_transactions
Fixes #
Ref #

feat(rpc): implement rpc api get_transactions

---

core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/utils.rs
core/storage/src/lib.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs
core/storage/src/relational/tests/get_cell_test.rs

feat(rpc): remove historical get_balance

---

core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/utils.rs
core/rpc/src/types.rs
core/storage/src/lib.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs

fix(storage): query transactions by script hashes

---

core/rpc/src/types.rs
core/storage/src/relational/fetch.rs

fix(rpc): fix build_detailed_cell

---

common/src/lib.rs
core/cli/src/lib.rs
core/rpc/src/ckb_client.rs
core/rpc/src/error.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl/query.rs
core/service/src/lib.rs
core/storage/src/lib.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/insert.rs
core/storage/src/relational/mod.rs
core/storage/src/relational/remove.rs
core/storage/src/relational/sql.rs
core/storage/src/relational/table.rs
core/storage/src/relational/tests/get_cell_test.rs
core/storage/src/relational/tests/mod.rs
core/synchronization/src/lib.rs
core/synchronization/src/sql.rs
core/synchronization/src/table.rs
db/xsql-test/src/sql.rs
devtools/create_table/create_sqlite_table.sql
devtools/create_table/create_table.sql

refactor(sync): extend cell table and deprecate consume info table

---

core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs

feat(rpc): add get ckb uri interface

---

core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/utils.rs

feat(rpc): Impl udt transfer in hold by from mode

---

common/src/utils.rs
core/rpc/src/rpc_impl/utils.rs
devtools/config/mainnet_config.toml
devtools/config/testnet_config.toml

fix(rpc): debug dao conversion

---

core/rpc/src/rpc_impl/utils.rs
core/storage/src/lib.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs

feat(storage): add query historical live cell interface

---

core/rpc/src/indexer_types.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/type/indexer_legacy.rs

- refactor(rpc): unwrap indexer rpc api get_cells payload
- refactor(rpc): unwrap indexer rpc api get_cells_capacity payload
- refactor(rpc): unwrap indexer rpc api get_transactions payload
- refactor(rpc): change limit as Uint64 for indexer rpc api
Fixes #
Ref #

refactor(rpc): unwrap indexer rpc api's payload

---

core/rpc/src/rpc_impl/utils.rs
core/rpc/src/types.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs

fix(rpc): fix history get_balance

---

core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/utils.rs

feat(rpc): Impl transfer ckb in hold by to mode

---

core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/utils.rs

fix(rpc): debug get_transaction_info

---

core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/types/indexer_legacy.rs

* feat(rpc): implement legacy indexer rpc api get_live_cells_by_lock_hash
* refactor(rpc): move mod types::indexer
* refactor(rpc): format- feat(rpc): implement legacy indexer rpc api get_capacity_by_lock_hash
- feat(rpc): implement legacy indexer rpc api get_capacity_by_lock_hash
- resolve conflict
Fixes #
Ref #

feat(rpc): implement legacy indexer rpc api get_capacity_by_lock_hash

---

core/rpc/src/rpc_impl/query.rs
core/rpc/src/types.rs

fix(rpc): enable negative fee

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/consts.rs

fix(rpc): fix build_deposit_transaction

---

core/rpc/src/rpc_impl/build_tx.rs

refactor(rpc): return change_fee_cell_index

---

Cargo.lock
core/rpc/src/rpc_impl/adjust_account.rs
core/rpc/src/rpc_impl/build_tx.rs

refactor(rpc): change update adjust  account change cell

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/utils.rs

fix(rpc): fix build_withdraw

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/utils.rs
core/rpc/src/types.rs

feat(rpc): Impl smart transfer

---

core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/utils.rs
core/rpc/src/types.rs
devtools/create_table/create_table.sql

fix(rpc): debug build_transfer_transaction

---

core/rpc/src/rpc_impl/query.rs
core/rpc/src/types/indexer.rs

fix(rpc): fix get transaction cell logic

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl/build_tx.rs

fix(rpc): add check after get_live_cells_by_item

---

core/rpc/src/rpc_impl/adjust_account.rs
core/rpc/src/rpc_impl/utils.rs

fix(rpc): change output acp cell data

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl/adjust_account.rs
core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/utils.rs
core/rpc/src/types/indexer.rs
devtools/config/mainnet_config.toml
devtools/config/testnet_config.toml

fix(rpc): debug get_balance and build_transfer_transaction

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/utils.rs

fix(rpc): skip lock_hashes is empty

---

core/rpc/src/rpc_impl/build_tx.rs
devtools/create_table/create_table.sql

fix(rpc): add indexer for consumend_tx_hash in cell table

---

core/rpc/src/error.rs
core/rpc/src/rpc_impl/adjust_account.rs

fix(rpc): split acp cells and calculate actual fee

---

core/rpc/src/rpc_impl/build_tx.rs

fix(rpc): add sUDT cell_deps for transfer transaction

---

core/rpc/src/rpc_impl/adjust_account.rs
core/rpc/src/rpc_impl/utils.rs

fix(rpc): add change cell of build account output

---

common/src/lib.rs
core/rpc/src/error.rs
core/rpc/src/rpc_impl/utils.rs

fix(rpc): fix claimable

---

core/rpc/src/rpc_impl/query.rs

fix(rpc): fix get_spend_transaction

---

Cargo.lock
core/rpc/src/lib.rs
core/service/src/lib.rs
core/storage/src/relational/fetch.rs

fix(storage): fetch cell between block range

---

core/rpc/src/rpc_impl/adjust_account.rs

fix(rpc): update change cell in transaction view

---

common/src/address.rs
core/rpc/README.md
core/rpc/src/error.rs
core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/utils.rs

fix(rpc): debug build_smart_transaction

---

core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs

fix: fetch transaction with pagination request

---

core/rpc/README.md
core/rpc/src/error.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/adjust_account.rs
core/rpc/src/rpc_impl/utils.rs

fix(rpc): debug build_adjust_account_transaction

---

common/src/lib.rs
core/storage/src/relational/fetch.rs
db/xsql/src/page.rs

fix(storage): next cursor of pagination response

---

common/src/lib.rs

refactor(common): change default order to ascend 

---

README.md
db/xsql/src/page.rs

docs: update README

---

apm/tracing/Cargo.toml
core/rpc/Cargo.toml
core/storage/Cargo.toml
core/storage/src/relational/fetch.rs
db/xsql/Cargo.toml

refactor: change next cursor of pagination

---

core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/utils.rs

fix(rpc): fix get_live_cell by record id

---

core/storage/src/relational/fetch.rs
core/storage/src/relational/tests/get_block_test.rs

fix(storage): build epoch full value of block view

---

core/storage/src/relational/fetch.rs

fix(storage): recover Byte32 from database

---

core/storage/src/relational/fetch.rs
core/storage/src/relational/tests/get_block_test.rs

fix(storage): fix unit test test_get_block_header_by_number

---

core/storage/src/relational/fetch.rs
core/storage/src/relational/tests/get_block_test.rs

fix(db): add test test_get_genesis_block_header

---

core/rpc/src/rpc_impl/build_tx.rs
devtools/config/testnet_config.toml

fix(rpc): fix dao withdraw

---

core/rpc/src/ckb_client.rs
core/rpc/src/error.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl/build_tx.rs
core/service/src/lib.rs

fix(rpc): fix update current_epoch_number

---

common/src/address.rs

fix(common): fix pubkey too long cause panic

---

core/rpc/src/rpc_impl/build_tx.rs

feat(rpc): split change cell to ckb change and udt change

---

.github/workflows/release.yml

refactor: change release action

---

Cargo.lock
Cargo.toml
apm/tracing/Cargo.toml
core/cli/Cargo.toml
core/inspection/Cargo.toml
core/rpc/Cargo.toml
core/rpc/src/error.rs
core/rpc/src/rpc_impl/adjust_account.rs
core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/rpc_impl/query.rs
core/rpc/src/rpc_impl/utils.rs
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml

refactor(rpc): remove unwrap instead of return error

---

Cargo.lock
common/Cargo.toml
common/src/lib.rs
core/cli/src/lib.rs
core/storage/src/relational/mod.rs

feat(cli): add some cmd args for mercury

---

core/rpc/src/rpc_impl/build_tx.rs

fix(rpc): fix return error

---

Cargo.lock
README.md
core/cli/src/config.rs
core/cli/src/lib.rs
core/service/src/lib.rs
core/synchronization/src/lib.rs
core/synchronization/src/sql.rs
core/synchronization/src/table.rs
devtools/config/docker_compose_config.toml
devtools/config/mainnet_config.toml
devtools/config/testnet_config.toml
devtools/create_table/create_table.sql

refactor: remove rocksdb and refactor sync process

---

Cargo.lock
core/synchronization/Cargo.toml
core/synchronization/src/lib.rs
core/synchronization/src/sql.rs

feat(sync): paginate update and insert into by block number

---

core/storage/src/relational/remove.rs

fix(storage): rollback block method

---

core/rpc/src/lib.rs
core/service/src/lib.rs
core/storage/src/relational/mod.rs
core/synchronization/src/lib.rs
core/synchronization/src/sql.rs

feat(service): add a check of db tip and node tip

---

core/rpc/src/rpc_impl/utils.rs
core/rpc/src/tests/utils_test.rs

fix utils::to_since method.
Fixes #
Ref #

fix(rpc): utils::to_since function

---

common/src/lib.rs
core/storage/src/relational/mod.rs

chore: remove useless monitor code

---

Cargo.lock
Cargo.toml
common/Cargo.toml
core/cli/Cargo.toml
core/extensions/Cargo.toml
core/inspection/Cargo.toml
core/rpc/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml

release v0.2.0-beta.3 version
Fixes #
Ref #

chore: release v0.2.0-beta.3 version

---

core/rpc/README.md

update rpc readme doc：
- redefine SignatureAction 
- redefine Dao-related rcp interface.
- redefine epoch_number in Record
Fixes #
Ref #

docs(rpc): update rpc README document

---

devtools/create_table/create_table.sql

Change the create table index sql
Fixes #
Ref #

chore(sql): update create table index sql

---

core/rpc/README.md
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/tests/mod.rs
core/rpc/src/types.rs

Rename the rpc interface name `build_smart_transfer_transaction` to `build_simple_transfer_transaction`
Fixes #
Ref #
Breaking Change: rename the rpc interface name `build_smart_transfer_transaction` to `build_simple_transfer_transaction`

feat(rpc): rename rpc build_smart_transfer_transaction

---

core/rpc/README.md

docs(rpc): update rpc doc

---

core/rpc/src/rpc_impl/query.rs
core/rpc/src/types.rs

feat(rpc): forbidden negetive fee

---

Cargo.lock
core/rpc/Cargo.toml
core/rpc/src/rpc_impl/query.rs
core/rpc/src/tests/operation_test.rs
core/service/src/lib.rs
core/storage/Cargo.toml
core/storage/src/lib.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/insert.rs
core/storage/src/relational/mod.rs
core/storage/src/relational/remove.rs
core/storage/src/relational/sql.rs
core/storage/src/relational/table.rs
core/storage/src/relational/tests/get_cell_test.rs
core/storage/src/relational/tests/mod.rs
core/storage/src/relational/tests/other_test.rs
core/synchronization/Cargo.toml
core/synchronization/src/lib.rs
core/synchronization/src/sql.rs
core/synchronization/src/table.rs
db/xsql-test/Cargo.toml
db/xsql-test/src/lib.rs
db/xsql-test/src/sql.rs
db/xsql/Cargo.toml
db/xsql/src/lib.rs
db/xsql/src/page.rs
devtools/create_table/create_table.sql

Develop the synchronization of indexer cell table. For detail, see #285 .
Fixes #
Ref #

feat(sync): develop the synchronization of indexer cell table

---

core/rpc/src/rpc_impl/utils.rs

fix bug: pool_live_cells_by_items repeatedly pool udt for each item.
Fixes #
Ref #

fix(rpc): pool_live_cells_by_items repeatedly pool udt for each item

---

core/rpc/src/rpc_impl/utils.rs

fix bug: pool_live_cells_by_items pool ckb just from first item
Fixes #
Ref #

fix(rpc): pool_live_cells_by_items pool ckb just from first item

---

README.md
common/src/lib.rs
common/src/utils.rs
core/cli/src/config.rs
core/cli/src/lib.rs
core/rpc/src/lib.rs
core/storage/src/relational/mod.rs
db/xsql/src/page.rs
devtools/config/docker_compose_config.toml
devtools/config/mainnet_config.toml
devtools/config/testnet_config.toml
docs/config.md

Add the document of config instrcution.
Fixes #
Ref #

docs(config): add the document of config instruction

---

Cargo.lock
Cargo.toml
common/Cargo.toml
core/cli/Cargo.toml
core/extensions/Cargo.toml
core/inspection/Cargo.toml
core/rpc/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml

chore: release v0.2.0-beta.4 version

---

core/rpc/README.md
core/rpc/src/error.rs
core/rpc/src/lib.rs
core/rpc/src/rpc_impl.rs
core/rpc/src/rpc_impl/build_tx.rs
core/rpc/src/types.rs

To help developers test their code, this PR adds support for building sUDT issuing transactions in Mercury.
Fixes #
Ref #

feat(rpc): implement `build_sudt_issue_transaction`

---

README.md
docs/setup.md

This PR contains more detailed setup instructions.

docs: add detailed setup instructions

---

Cargo.lock
core/storage/src/relational/sql.rs

fix(storage): get db tip from block table

---

Cargo.lock
core/storage/src/relational/mod.rs
core/storage/src/relational/sql.rs
core/storage/src/relational/table.rs
devtools/create_table/create_table.sql

refactor(sql): change sql return type and index type

---

core/storage/src/relational/insert.rs

For addresses registered through register_addresses repeatedly, no error should be reported, and lock_hash should be returned directly. The statelessness of calling register_addresses can improve the user experience.
Fixes #
Ref #

fix(rpc): support repeated address registration

---

common/src/address.rs
core/rpc/core/src/error.rs
core/rpc/core/src/impl/utils.rs
core/rpc/types/src/error.rs
core/rpc/types/src/lib.rs

Return error instead of unreachable!() when handle rpc.
Fixes #
Ref #

fix(rpc): return error instead unreachable!()

---

Cargo.lock
common/src/address.rs
common/src/utils.rs
core/rpc/core/src/impl/adjust_account.rs
core/rpc/core/src/impl/utils.rs

Parse address from script will generate full address now.
Fixes #
Ref #

refactor(common): use full address global

---

core/rpc/README.md

docs(RPC): update RPC module README

---

Cargo.lock
Cargo.toml
README.md
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/inspection/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/types/Cargo.toml
core/rpc/utility/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml
docs/migration.md
docs/setup.md
extensions/mnft/Cargo.toml
extensions/xudt/Cargo.toml
protocol/Cargo.toml

chore: release v0.2.0

---

core/service/src/lib.rs

fix overflow panic when do_sync.
Fixes #
Ref #

fix(service): overflow panic when do_sync

---

core/service/src/lib.rs

Release mercury v0.2.0 version.
Fixes #
Ref #

chore: release mercury 0.2.0 version

---

core/rpc/core/src/impl/utils.rs
core/service/src/lib.rs

Fix overflow when calculate acp cell extra capacity when building transfer tx.
Fixes #
Ref #

fix(rpc): build transfer overflow

---

core/rpc/core/src/impl/build_tx.rs

Refactor `build_sudt_issue_transaction` API by `balance_transfer_tx`.
Fixes #
Ref #

feat: refactor `build_sudt_issue_transaction`

---

Cargo.lock
core/cli/src/lib.rs
core/rpc/README.md
core/rpc/core/src/error.rs
core/rpc/core/src/impl.rs
core/rpc/core/src/impl/query.rs
core/rpc/core/src/impl/utils.rs
core/rpc/core/src/lib.rs
core/rpc/core/src/tests/mod.rs
core/rpc/core/src/tests/utils_test.rs
core/rpc/types/src/lib.rs
core/service/src/lib.rs
core/storage/src/lib.rs
core/storage/src/relational/mod.rs
core/synchronization/Cargo.toml
core/synchronization/src/lib.rs

Add rpc get_sync_state, to get the state of synchronization.
Fixes #
Ref #

feat(rpc): add rpc get_sync_state

---

core/cli/src/lib.rs

Fix sync mode: only when sync mode is turned on will the synchronization operation be performed.
Fixes #
Ref #

fix(cli): sync mode logic

---

core/rpc/core/src/impl/utils.rs
core/rpc/core/src/impl/utils_types.rs

Support secp udt cell to pool ckb.
Fixes #
Ref #

feat(rpc): support secp udt cell to pool ckb

---

core/rpc/core/src/error.rs
core/rpc/core/src/impl/build_tx.rs
core/rpc/core/src/impl/utils.rs
core/storage/src/error.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs

Improve error info:
- CoreError::CkbIsNotEnough
- CoreError::UdtIsNotEnough
- DBError::NotExist
Fixes #
Ref #

chore: Improve error info

---

core/rpc/core/src/impl/build_tx.rs

refactor(rpc): update build dao related rpc with new pool method:
- build_dao_deposit_transaction
- build_dao_withdraw_transaction
Fixes #
Ref #

refactor(rpc): update build dao with new pool method

---

core/rpc/core/src/impl/adjust_account.rs
core/rpc/core/src/impl/build_tx.rs
core/rpc/core/src/impl/utils.rs

Refactor `build_adjust_account_transaction` API by `balance_transfer_tx`.
Fixes #
Ref #

refactor(rpc): use balance method for `build_adjust_account_transaction`

---

core/service/src/lib.rs
core/storage/src/relational/insert.rs

Add time duration log when append and insert cell table
Fixes #
Ref #

chore: add time duration log when append and insert cell table

---

core/rpc/core/src/impl/build_tx.rs
core/rpc/core/src/impl/utils.rs
core/service/src/lib.rs
core/storage/src/relational/insert.rs

Fix dao withdraw tx signature error.
Fixes #
Ref #

fix(rpc): dao withdraw signature error

---

core/rpc/core/src/impl/utils.rs

Add type check when seek change on tx output.
Fixes #
Ref #

fix(rpc): add type check when seek change on tx output

---

Cargo.lock
Cargo.toml
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/inspection/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/types/Cargo.toml
core/rpc/utility/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml
docs/migration.md
docs/setup.md
extensions/mnft/Cargo.toml
extensions/xudt/Cargo.toml
protocol/Cargo.toml

chore: release v0.2.1

---

core/rpc/README.md
core/storage/src/relational/_sql.html
core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs
core/storage/src/relational/tests/other_test.rs

Fix rpc query_transactions limt semantic error.
Fixes #
Ref #

fix(rpc): query_transactions limt semantic error

---

core/rpc/core/src/impl/utils.rs
core/storage/src/lib.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs
core/storage/src/relational/tests/get_tx_test.rs
protocol/src/db.rs

Fix rpc query_transaction bug when input record as item.
Fixes #
Ref #

fix(rpc): query_transaction with record item

---

tests/tests/rpc/build_adjust_account_transaction.rs
tests/tests/rpc/build_dao_deposit_transaction.rs
tests/tests/rpc/build_dao_withdraw_transaction.rs
tests/tests/rpc/build_simple_transfer_transaction.rs
tests/tests/rpc/build_transfer_transaction.rs
tests/tests/rpc/common.rs
tests/tests/rpc/get_balance.rs
tests/tests/rpc/get_block_info.rs
tests/tests/rpc/get_db.rs
tests/tests/rpc/get_mercury_info.rs
tests/tests/rpc/get_spent_transaction.rs
tests/tests/rpc/get_sync_state.rs
tests/tests/rpc/get_transaction_info.rs
tests/tests/rpc/mod.rs
tests/tests/rpc/query_transactions.rs

Fix integration test cases.
Fixes #
Ref #

chore: fix integration test cases

---

Cargo.lock
Cargo.toml
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/inspection/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/types/Cargo.toml
core/rpc/utility/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml
docs/migration.md
docs/setup.md
extensions/mnft/Cargo.toml
extensions/xudt/Cargo.toml
protocol/Cargo.toml

chore: release v0.2.2

---

core/rpc/core/src/impl/query.rs
core/service/src/lib.rs
core/storage/src/lib.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs
core/storage/src/relational/sql.rs
core/synchronization/src/lib.rs

User can acquire progress on the second parallelly sync stage now.
Fixes #
Ref #

feat: compute progress on `ParallelSecondStage`

---

apm/tracing-derive/src/attr_parse.rs
core/rpc/core/src/impl/adjust_account.rs
core/rpc/core/src/impl/build_tx.rs
core/rpc/core/src/impl/query.rs
core/rpc/core/src/impl/utils.rs
core/rpc/core/src/tests/utils_test.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/table.rs

Refactoring code.
Fixes #
Ref #

chore: refactoring code

---

Cargo.lock
core/cli/src/config.rs
core/cli/src/lib.rs
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/core/src/impl.rs
core/rpc/core/src/lib.rs
core/rpc/core/src/tests/mod.rs
core/service/src/lib.rs
devtools/config/mainnet_config.toml
devtools/config/testnet_config.toml

This PR integrates pprof into mercury for generating flame graph.
Fixes #
Ref #

feat: pprof flame graph

---

tests/tests/rpc/build_adjust_account_transaction.rs
tests/tests/rpc/build_dao_deposit_transaction.rs
tests/tests/rpc/build_simple_transfer_transaction.rs
tests/tests/rpc/build_sudt_issue_transaction.rs
tests/tests/rpc/build_transfer_transaction.rs
tests/tests/rpc/common.rs
tests/tests/rpc/mod.rs
tests/tests/rpc/query_transactions.rs

test: add more build_transfer_transaction integration test cases

---

tests/tests/rpc/build_dao_deposit_transaction.rs
tests/tests/rpc/build_simple_transfer_transaction.rs
tests/tests/rpc/build_transfer_transaction.rs
tests/tests/rpc/get_cells.rs
tests/tests/rpc/get_cells_capacity.rs
tests/tests/rpc/query_transactions.rs

chore: fix rpc tests 

---

core/rpc/core/src/impl/build_tx.rs
devtools/create_table/create_table.sql
docs/migration.md

- update db index creation script
- update the migration doc
- some fix
Fixes #
Ref #

chore: update db index creation script

---

core/rpc/core/src/impl/build_tx.rs
core/rpc/core/src/impl/utils.rs

Fix: failed to verify on test chain
Fixes #
Ref #

fix(rpc): failed to verify on test chain

---

Cargo.lock
Cargo.toml
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/inspection/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/types/Cargo.toml
core/rpc/utility/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml
docs/setup.md
extensions/mnft/Cargo.toml
extensions/xudt/Cargo.toml
protocol/Cargo.toml

chore: release v0.2.3

---

core/rpc/README.md
devtools/config/mainnet_config.toml
devtools/config/testnet_config.toml
devtools/my-postgres.conf
docker-compose.yml

- update rpc readme
- update docker-compose
Fixes #
Ref #

chore: update rpc readme and docker config

---

Cargo.lock
Cargo.toml
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/inspection/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/types/Cargo.toml
core/rpc/utility/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml
docs/migration.md
docs/setup.md
extensions/mnft/Cargo.toml
extensions/xudt/Cargo.toml
protocol/Cargo.toml

chore: release v0.2.4

---

core/rpc/core/src/impl/utils.rs
core/storage/src/lib.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs
core/storage/src/relational/tests/get_historical_live_cells_test.rs
core/storage/src/relational/tests/mod.rs
devtools/config/docker_compose_config.toml
tests/tests/rpc/build_transfer_transaction.rs

Add paging parameters and return values ​​to the DB layer method `get_historical_live_cells` to be consistent with the `get_live_cells` method.
Fixes #
Ref #

fix(db): get_historical_live_cells add pagination

---

core/rpc/core/src/impl/query.rs
core/rpc/core/src/impl/utils.rs
core/storage/src/lib.rs
core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs
core/storage/src/relational/tests/get_cell_test.rs
tests/tests/rpc/get_cells.rs
tests/tests/rpc/get_cells_capacity.rs

fix rpc get_cells and get_cells_capacity：
- invalid input filter：output_data_len_range
- invalid pagination for output_data_len_range and output_capacity_range
Fixes #
Ref #

fix(rpc): get_cells and get_cells_capacity

---

core/rpc/core/src/impl/utils.rs
core/storage/src/lib.rs
core/storage/src/relational/_sql.html
core/storage/src/relational/fetch.rs
core/storage/src/relational/mod.rs
core/storage/src/relational/sql.rs
core/storage/src/relational/tests/fetch_mod_test.rs
core/storage/src/relational/tests/get_tx_test.rs
core/storage/src/relational/tests/single_sql_test.rs
tests/tests/rpc/get_transactions.rs
tests/tests/rpc/query_transactions.rs

fix bugs:
- `query_transactions` with input `ExtraType::CellBase`
- `query_transactions` with input `ExtraType::Dao`
Fixes #
Ref #

fix(rpc): query_transactions by

---

core/rpc/core/src/impl/utils.rs

refactor: `balance_transfer_tx_capacity`

---

core/rpc/README.md
core/rpc/core/src/impl.rs
core/rpc/core/src/impl/adjust_account.rs
core/rpc/core/src/impl/build_tx.rs
core/rpc/core/src/impl/query.rs
core/rpc/core/src/impl/utils.rs
core/rpc/core/src/impl/utils_types.rs
core/rpc/core/src/tests/utils_test.rs
core/rpc/types/src/lib.rs
docs/migration.md
tests/tests/rpc/get_account_info.rs
tests/tests/rpc/get_balance.rs
tests/tests/rpc/query_transactions.rs

Rpc Breaking Change：
- in the `JsonItem` type, the enum value `OutPoint` replaces `Record`
- in the `Record` type, the `out_point` field replaces the `id` field
Fixes #
Ref #

refactor(rpc): out point replaces record id

---

core/rpc/core/src/impl/build_tx.rs
core/rpc/core/src/impl/utils.rs
tests/tests/rpc/build_transfer_transaction.rs

Removed restriction on to address when transferring CKB using HoldByFrom mode.
Fixes #
Ref #

fix(rpc): Removed restriction on to address when transferring ckb

---

Cargo.lock
Cargo.toml
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/inspection/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/types/Cargo.toml
core/rpc/utility/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml
docs/migration.md
docs/setup.md
extensions/mnft/Cargo.toml
extensions/xudt/Cargo.toml
protocol/Cargo.toml

chore: release v0.2.6

---

Cargo.lock
Cargo.toml
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/inspection/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/core/src/impl/build_tx.rs
core/rpc/core/src/impl/utils.rs
core/rpc/types/Cargo.toml
core/rpc/utility/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml
docs/migration.md
docs/setup.md
extensions/mnft/Cargo.toml
extensions/xudt/Cargo.toml
protocol/Cargo.toml
tests/tests/rpc/build_transfer_transaction.rs

Release mercury v0.2.6 version.
Fixes #
Ref #

chore: release mercury v0.2.6 version

---

core/rpc/README.md

fix(doc): correct errors in rpc readme

---

core/rpc/README.md

fix(doc): correct errors in rpc readme (#395)

---

core/rpc/README.md
core/rpc/core/src/impl/query.rs
core/rpc/core/src/impl/utils.rs
core/rpc/types/src/lib.rs
docs/migration.md
tests/tests/rpc/get_balance.rs

Breaking Change：rename filed `freezed` to `frozen` in the `Balance` structure
Fixes #
Ref #

chore(rpc): rename "freezed" to "frozen"

---

core/rpc/README.md
core/rpc/core/src/impl/build_tx.rs
core/rpc/core/src/impl/utils.rs
tests/tests/rpc/build_transfer_transaction.rs

chore: cherry pick dev branch update

---

Cargo.lock
Cargo.toml
README.md
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/inspection/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/types/Cargo.toml
core/rpc/utility/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml
docs/setup.md
extensions/mnft/Cargo.toml
extensions/xudt/Cargo.toml
protocol/Cargo.toml

chore: release v0.3.0

---

Cargo.lock
core/cli/src/lib.rs
core/rpc/core/Cargo.toml
core/service/Cargo.toml
core/service/src/lib.rs
core/synchronization/Cargo.toml
core/synchronization/src/lib.rs
core/synchronization/src/task.rs

fix(sync): reduce the memory usage in synchronization

---

Cargo.lock
Cargo.toml
README.md
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/cli/src/lib.rs
core/inspection/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/types/Cargo.toml
core/rpc/utility/Cargo.toml
core/service/Cargo.toml
core/service/src/lib.rs
core/storage/Cargo.toml
core/synchronization/Cargo.toml
core/synchronization/src/lib.rs
core/synchronization/src/task.rs
docker-compose.yml
docs/migration.md
docs/setup.md
extensions/mnft/Cargo.toml
extensions/xudt/Cargo.toml
protocol/Cargo.toml

- cherry pick fix(sync): reduce the memory usage in synchronization
- release v0.3.1
Fixes #
Ref #

chore: release v0.3.1

---

.gitignore
CHANGELOG.md
docs/migration.md

Add change log for 0.2 branch.
Fixes #
Ref #

chore: add change log for 0.2 branch

---

devtools/config/docker_compose_config.toml
devtools/config/mainnet_config.toml
devtools/config/testnet_config.toml
devtools/my-postgres.conf

- max_task_number in mercury config
- shared_buffers in my-postgres.conf
Fixes #
Ref #

chore: update config based on Recommended Hardware

---

core/rpc/README.md
core/rpc/core/src/impl/query.rs
core/rpc/core/src/impl/utils.rs
core/rpc/types/src/lib.rs
integration/src/tests/build_adjust_account_transaction.rs
integration/src/tests/build_dao_related_transaction.rs
integration/src/tests/build_simple_transfer_transaction.rs
integration/src/tests/build_transfer_transaction_ckb.rs
integration/src/tests/get_balance.rs
integration/src/utils/signer.rs
tests/tests/rpc/get_balance.rs

Rpc Type Breaking Change：
- revert the field ownership in Type Record and Balance
- change the type of the field ownership to String
Fixes #
Ref #

refactor(rpc): change the type of the field ownership to String in Type Record and Balance

---

docker-compose.yml

Update the ckb component in the docker-compose.yml to 0.103
Fixes #
Ref #

chore: update the ckb component  in the docker-compose.yml to 0.103

---

Cargo.lock
Cargo.toml
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/inspection/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/types/Cargo.toml
core/rpc/utility/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml
docs/migration.md
docs/setup.md
extensions/mnft/Cargo.toml
extensions/xudt/Cargo.toml
protocol/Cargo.toml

chore: release v0.2.7

---

Cargo.lock
Cargo.toml
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/inspection/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/types/Cargo.toml
core/rpc/utility/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml
docs/migration.md
docs/setup.md
extensions/mnft/Cargo.toml
extensions/xudt/Cargo.toml
protocol/Cargo.toml

chore: release v0.3.2

---

core/rpc/README.md

- fix `order` enum value
- update the url of the corresponding version of the mercury node
Fixes #
Ref #

fix(doc): rpc readme

---

core/rpc/README.md

* update mercury node url
* fix readme
Fixes #
Ref #

fix(doc): rpc readme (#419)

---

README.md
core/rpc/README.md
core/rpc/core/src/impl.rs
core/rpc/core/src/lib.rs
docs/migration.md

- update migration doc for 0.4.0
- update rpc `get_mercury_info`: get ckb node version dynamically
Fixes #
Ref #

chore(doc): update migration doc for 0.4.0

---

Cargo.lock
Cargo.toml
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/types/Cargo.toml
core/rpc/utility/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml
docs/migration.md
docs/setup.md
integration/Cargo.lock
protocol/Cargo.toml

- update v0.4.0 version
- add deprecated note for rpc `register_addresses`
Fixes #
Ref #

chore: release v0.4.0

---

CHANGELOG.md

Release mercury v0.4.0 version.
Fixes #
Ref #

chore: release mercury v0.4.0 version

---

core/rpc/README.md

Add more detailed description for `ExtraFilter`.
Fixes #
Ref #

chore(doc): add more detailed description for `ExtraFilter`

---

core/storage/src/relational/fetch.rs

fix(rpc): transactions generated by rpc `build_dao_claim_transaction` will cause random -14 dao script validation error 
Fixes #
Ref #

fix(rpc): transactions generated by rpc `build_dao_claim_transaction` will cause random -14 dao script validation error 

---

core/storage/src/relational/fetch.rs

…ill cause random -14 dao script validation error
fix(rpc): transactions generated by rpc build_dao_claim_transaction will cause random -14 dao script validation error
Fixes #
Ref #

fix(rpc): transactions generated by rpc build_dao_claim_transaction will cause random -14 dao script validation error

---

CHANGELOG.md
Cargo.lock
Cargo.toml
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/types/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml
docs/migration.md
docs/setup.md
integration/Cargo.lock
protocol/Cargo.toml

chore: release v0.4.2

---

core/rpc/README.md
core/rpc/core/src/impl/utils.rs
integration/src/tests/build_dao_related_transaction.rs

Fix get_balance for withdrawing cell.
Fixes #
Ref #

fix(rpc): fix get_balance for withdrawing cell

---

CHANGELOG.md
Cargo.lock
Cargo.toml
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/types/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml
docs/migration.md
docs/setup.md
integration/Cargo.lock
protocol/Cargo.toml

chore: release v0.4.3

---

core/rpc/README.md
core/rpc/core/src/impl/utils.rs

Fix Mercury 0.3.x get_balance for withdrawing cell.
Fixes #
Ref #

fix(rpc): fix Mercury 0.3.x get_balance for withdrawing cell 

---

core/rpc/README.md
core/rpc/core/src/impl/utils.rs

Fix Mercury 0.2.x get_balance for withdrawing cell.
Fixes #
Ref #

fix(rpc): fix Mercury 0.2.x get_balance for withdrawing cell

---

CHANGELOG.md
Cargo.lock
Cargo.toml
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/inspection/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/types/Cargo.toml
core/rpc/utility/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml
docs/migration.md
docs/setup.md
extensions/mnft/Cargo.toml
extensions/xudt/Cargo.toml
protocol/Cargo.toml

chore: release v0.3.4

---

CHANGELOG.md
Cargo.lock
Cargo.toml
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/inspection/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/types/Cargo.toml
core/rpc/utility/Cargo.toml
core/service/Cargo.toml
core/storage/Cargo.toml
core/synchronization/Cargo.toml
docker-compose.yml
docs/migration.md
docs/setup.md
protocol/Cargo.toml

chore: release v0.2.9

---

core/rpc/README.md
core/rpc/core/src/impl/query.rs
core/rpc/types/src/lib.rs
core/storage/src/relational/insert.rs
integration/src/tests/build_adjust_account_transaction.rs
integration/src/tests/build_dao_related_transaction.rs
integration/src/tests/build_simple_transfer_transaction.rs
integration/src/tests/build_sudt_issue_transaction.rs
integration/src/tests/build_transfer_transaction_ckb.rs
integration/src/tests/build_transfer_transaction_ckb_pw.rs
integration/src/tests/build_transfer_transaction_udt.rs
integration/src/tests/get_balance.rs

Add `extra` input para in rpc `get_balance`.
Fixes #
Ref #

feat(rpc): add `extra` para in rpc `get_balance`

---

CHANGELOG.md
Cargo.lock
Cargo.toml
common/Cargo.toml
core/ckb-client/Cargo.toml
core/cli/Cargo.toml
core/rpc/README.md
core/rpc/core/Cargo.toml
core/rpc/core/src/impl/query.rs
core/rpc/types/Cargo.toml
core/rpc/types/src/lib.rs
core/service/Cargo.toml
core/storage/Cargo.toml
core/storage/src/relational/insert.rs
core/synchronization/Cargo.toml
docker-compose.yml
docs/migration.md
docs/setup.md
integration/Cargo.lock
integration/src/tests/build_adjust_account_transaction.rs
integration/src/tests/build_dao_related_transaction.rs
integration/src/tests/build_simple_transfer_transaction.rs
integration/src/tests/build_sudt_issue_transaction.rs
integration/src/tests/build_transfer_transaction_ckb.rs
integration/src/tests/build_transfer_transaction_ckb_pw.rs
integration/src/tests/build_transfer_transaction_udt.rs
integration/src/tests/get_balance.rs
protocol/Cargo.toml

Release mercury v0.4.4 version.
Fixes #
Ref #

chore: release mercury v0.4.4 version
