nervosnetwork/mercury

src/cli.rs, src/extensions/ckb_balance/mod.rs, src/extensions/udt_balance/mod.rs, src/service.rs, src/utils.rs
If the extension cannot get a cell from ckb-indexer, the cell may point to an output cell in the same transaction. Extensions check whether the block transaction list contains the input cell transaction hash. Otherwise, get the cell from ckb-indexer.
Fixes #
Ref #
=> fix: input cell point to a forward output cell in same tx

Cargo.lock, src/extensions/udt_balance/mod.rs, src/extensions/udt_balance/types.rs
Add is_sudt flag in Value::script. So that mercury can judge whether an udt_hash is of SUDT or not.
Fixes #
Ref #
=> refactor(udt): add is_sudt flag in script value

core/rpc/src/lib.rs, core/rpc/src/rpc_impl.rs, core/rpc/src/rpc_impl/query.rs, core/rpc/src/tests/query_test.rs, core/rpc/src/types.rs
Change the `udt_hash` argument to a `Vec`.
Change the rpc response to a `Vec`.
Fixes #
Ref #
=> refactor(rpc): get balance interface argument and response

Cargo.lock, common/src/address.rs, core/rpc/src/error.rs, core/rpc/src/lib.rs, core/rpc/src/rpc_impl.rs, core/rpc/src/rpc_impl/query.rs, core/rpc/src/rpc_impl/transfer.rs, core/rpc/src/tests/mod.rs, core/rpc/src/tests/query_test.rs, core/rpc/src/types.rs, core/service/src/lib.rs
1. Change the argument of the `get_balance` interface to a struct.
2. Change the `udt_hashes` to a `HashSet`, if it is empty, means to get the balance of all assets.
Fixes #
Ref #
=> refactor(rpc): change the  get balance interface

core/extensions/src/lib.rs, core/extensions/src/script_hash/mod.rs, core/extensions/src/script_hash/types.rs, core/extensions/src/tests/mod.rs, core/rpc/src/lib.rs, core/rpc/src/rpc_impl.rs, core/rpc/src/tests/mod.rs, core/rpc/src/tests/operation.rs, devtools/config/mainnet_config.toml, devtools/config/testnet_config.toml
1. Add script hash extension to index any script with its blake160 hash in output.
2. Add register address RPC interface.
Fixes #
Ref #
=> feat: add script hash extension and register address rpc interface

Cargo.lock, core/rpc/src/ckb_client.rs, core/rpc/src/error.rs, core/rpc/src/lib.rs, core/rpc/src/rpc_impl.rs, core/rpc/src/rpc_impl/operation.rs, core/rpc/src/rpc_impl/query.rs, core/rpc/src/rpc_impl/transfer.rs, core/rpc/src/types.rs
=> feat(rpc): add get generic transaction and generic block interface

core/rpc/src/error.rs, core/rpc/src/lib.rs, core/rpc/src/rpc_impl.rs, core/rpc/src/rpc_impl/query.rs, core/rpc/src/rpc_impl/transfer.rs, core/rpc/src/types.rs
=> feat(rpc): build asset collection transaction

core/storage/src/relational/insert.rs, core/storage/src/relational/mod.rs, core/storage/src/relational/table.rs
=> fix(storage): update consumed info at the end of append

Cargo.lock, Cargo.toml, apm/tracing/Cargo.toml, core/cli/Cargo.toml, core/inspection/Cargo.toml, core/rpc/Cargo.toml, core/rpc/src/ckb_client.rs, core/rpc/src/rpc_impl/query.rs, core/service/Cargo.toml, core/storage/Cargo.toml, core/storage/src/relational/insert.rs, core/storage/src/relational/mod.rs, core/synchronization/Cargo.toml, core/synchronization/src/lib.rs, db/xsql/src/lib.rs, devtools/create_table/create_table.sql
1. Add build index SQL of `block_number` and `consumed_block_number` in `mercury_cell` table.
2. After building the indexer cells of the corresponding block number range, insert them into the database immediately.
Fixes #
Ref #
=> refactor(sync): change build indexer cell table process

core/rpc/src/rpc_impl/adjust_account.rs
Fix signature_actions in build_adjust_account_transaction, other_indexes_in_group is empty when inputs are more than one.
Fixes #
Ref #
=> fix(rpc): Fix signature_actions in build_adjust_account_transaction

core/rpc/src/error.rs, core/rpc/src/rpc_impl/build_tx.rs
Bug: build_dao_claim_transaction panic when no unlocked withdrawing cells was found.
Fixes #
Ref #
=> fix(rpc): build_dao_claim_transaction panic

Cargo.lock, core/service/src/lib.rs
Fix mercury always goto synchronization when restart. The reason is that there is a bug at calculate the gap of ckb node and mercury.
Fixes #
Ref #
=> fix: always goto synchronization when restart

core/rpc/README.md, core/rpc/src/rpc_impl/query.rs, core/rpc/src/types.rs, core/storage/src/relational/fetch.rs, core/storage/src/relational/tests/get_tx_test.rs, db/protocol/src/lib.rs
When rpc `query_transactions` is called, the time stamp information will be newly added to the returned TransactionInfo.
```rust
pub struct TransactionInfo {
...
pub timestamp: u64, 
}
```
Fixes #
Ref #
=> feat(rpc): add timestamp to TransactionInfo.

core/rpc/README.md, core/rpc/src/rpc_impl/query.rs, core/rpc/src/types.rs
Add timestamp for rpc query_transactions with native structure_type.
Fixes #
Ref #
Breaking Change: 
```rust
async fn query_transactions(
&self,
payload: QueryTransactionsPayload,
) -> RpcResult<PaginationResponse<TxView>>;
pub enum TxView {
TransactionView(TransactionWithRichStatus), // modify: replace TransactionWithStatus
TransactionInfo(TransactionInfo),
}
// new
pub struct TransactionWithRichStatus {
pub transaction: Option<TransactionView>,
pub tx_status: TxRichStatus,
}
// new
pub struct TxRichStatus {
pub status: Status,
pub block_hash: Option<H256>,
pub reason: Option<String>,
pub timestamp: Option<u64>,
}
```
**Special notes for your …
=> feat(rpc): add timestamp for rpc query_transactions when native type

core/rpc/README.md, core/rpc/src/error.rs, core/rpc/src/rpc_impl/adjust_account.rs, core/rpc/src/rpc_impl/build_tx.rs, core/rpc/src/rpc_impl/utils.rs, core/rpc/src/tests/utils_test.rs, core/rpc/src/types.rs
In Mercury 0.2.0 (beta3 and before), the pool_live_cells_by_items method will output duplicate cells in the following situations:
- Input parameter items: Vec, there are duplicate items;
- Input parameter items: Vec, while mixing Identity, Address and Record, at this time they may parse out duplicate lock hash for cell search
- Inside pool_live_cells_by_items: pool normal_ckb_cells logic includes pool cell_base_cells. When there is a "miner" item in the input parameter, duplicate cells will be output
In this PR:
- At the entrance of the rpc interface, perform deduplication of items> and check the same type of enumeration (that is, all are Identity, or all are Address, or all are Record)
- Involved rpc: build_adjust_account_transaction …
=> fix(rpc): pool duplicate cells

core/rpc/README.md
The addition of timestamp in TransactionWithRichStatus affects the return value of rpc get_spent_transaction.
Fixes #
Ref #
=> docs(rpc): update rpc get_spent_transaction result.

core/rpc/README.md, core/rpc/src/rpc_impl/build_tx.rs, core/rpc/src/rpc_impl/query.rs, core/rpc/src/rpc_impl/utils.rs, core/rpc/src/types.rs
- Improve rpc json output format
- Rename enum AddressOrLockHash to Ownership
Fixes #
Ref #
Breaking Change:
```rust
#[serde(tag = "type", content = "value")]
pub enum Ownership {  // rename AddressOrLockHash
Address(String),
LockHash(String),
}
#[serde(tag = "type", content = "value")]
pub enum Status {
Claimable(BlockNumber),
Fixed(BlockNumber),
}
#[serde(tag = "type", content = "value")]
pub enum ExtraFilter {
Dao(DaoInfo),  // {"type": "Dao", value: "..."}
CellBase,  // {"type": "CellBase"}
}
#[serde(tag = "type", content = "value")]
pub enum DaoState {
Deposit(BlockNumber),
Withdraw(BlockNumber, BlockNumber),
}
#[serde(tag = "type", content …
```
=> feat(rpc): improve rpc json output format

Cargo.lock, Cargo.toml, apm/tracing/Cargo.toml, core/cli/Cargo.toml, core/inspection/Cargo.toml, core/rpc/Cargo.toml, core/rpc/src/tests/rpc_test.rs, core/service/Cargo.toml, core/storage/Cargo.toml, core/storage/src/relational/mod.rs, core/storage/src/relational/remove.rs, core/storage/src/relational/sql.rs, core/synchronization/Cargo.toml, db/xsql/Cargo.toml, db/xsql/src/page.rs, devtools/create_table/create_table.sql
1. Fix get tx_hash process when query transaction by script. Use the distinct keyword.
2. Build index on mercury_indexer_cell table tx_hash column.
3. Bump tokio version to 1.14
4. Change bson to bson2 which supports u64.
Fixes #
Ref #
=> fix(storage): get tx_hash when query transaction by script

core/storage/src/relational/mod.rs, core/synchronization/src/lib.rs, db/xsql/src/lib.rs, src/main.rs
Rollback tx when failed rather than close connection
Fixes #
Ref #
=> refactor(DB): rollback tx when failed rather than close connection

core/rpc/README.md, core/rpc/core/src/impl/utils.rs, core/rpc/types/src/lib.rs
Change the definition of occupied and free in the `get_balance` interface.
Fixes #
Ref #
=> feat(rpc): change the definition of occupied and free

core/rpc/core/src/impl/utils.rs, core/service/src/lib.rs
Fix pool next at dao claim cell panic.
Fixes #
Ref #
=> fix(rpc): pool next at dao claim cell panic

core/rpc/core/src/error.rs, core/rpc/core/src/impl/adjust_account.rs
Let `Mercury` supports recycling all ACP cells, which means adjust accounts number to 0. This operation requires **NO** UDT assets was holded by the address.  
Fixes #
Ref #
=> feat: support recycling all ACP cells

core/rpc/core/src/impl/utils.rs, core/storage/src/lib.rs, core/storage/src/relational/fetch.rs, core/storage/src/relational/mod.rs
- fix bug: get_balance return null when record id encoded based on short address
- fix bug: get_live_cells did not filter out point when tip_block_number specified
- fix bug: lack of filters in query_live_cells 
Fixes #
Ref #
=> fix(rpc): get_balance return error when pass record

core/storage/src/relational/fetch.rs
Fix build_next_cursor error when order is desc.
Fixes #
Ref #
=> fix(db): build_next_cursor error when order is desc

tests/README.md, tests/tests/rpc/get_cells.rs, tests/tests/rpc/get_cells_capacity.rs, tests/tests/rpc/get_tip.rs, tests/tests/rpc/get_transactions.rs, tests/tests/rpc/mod.rs
=> feat: Add indexer API test cases

core/rpc/core/src/impl/utils.rs, tests/tests/rpc/get_balance.rs, tests/tests/rpc/query_transactions.rs
Fix get_balance statistics for acp and pw lock cell without type script, considering that for acp cell and pw lock cell without type script, full capacity can be provided when pooling money.
Fixes #
Ref #
=> fix(rpc): fix get_balance statistics for acp and pw lock cell without type script

core/synchronization/src/sql.rs
Re-create table should re-create index too. Otherwise, when Mercury is restarted and the parallel synchronization is performed again, the indexes of more than one tables will be lost, and the insertion will be too slow to keep up with the ckb node.
Fixes #
Ref #
=> fix(sync): re-create table should re-create index too

core/rpc/README.md, core/rpc/core/src/error.rs, core/rpc/core/src/impl.rs, core/rpc/core/src/impl/adjust_account.rs, core/rpc/core/src/impl/build_tx.rs, core/rpc/core/src/impl/utils.rs, core/rpc/core/src/lib.rs, core/rpc/types/src/lib.rs, tests/tests/rpc/build_adjust_account_transaction.rs, tests/tests/rpc/build_transfer_transaction.rs, tests/tests/rpc/get_account_info.rs, tests/tests/rpc/mod.rs
- add new transfer mode `PayWithAcp`: In the new `Paywithacp` mode, when transferring UDT assets, the CKBytes provided by the sender will belongs to the receiver. This is the difference from the `HoldByFrom` mode implemented by cheque lock.
- add new rpc `get_account_info`: with this rpc, you can check whether the receiver has a udt account before transferring udt. If there is, you can use the most convenient `HoldByTo` mode, if not, you can use `HoldbyFrom` or `PayWithAcp` mode according to the situation.
Fixes #
Ref #
=> feat(rpc): add new transfer mode PayWithAcp and new rpc get_account_info

core/service/src/lib.rs, core/storage/src/relational/mod.rs, core/synchronization/src/lib.rs
fix(sync): Mercury will fail to start when the database is newly created and the difference between node height and local db height is less than the threshold.
Fixes #
Ref #
=> fix(sync): mercury fail to start

core/rpc/README.md, core/rpc/core/src/impl/adjust_account.rs, core/rpc/core/src/impl/build_tx.rs, core/rpc/core/src/impl/utils.rs, core/rpc/core/src/tests/rpc_test.rs, core/rpc/core/src/tests/utils_test.rs, core/rpc/types/src/lib.rs, integration/src/tests/build_adjust_account_transaction.rs, integration/src/tests/build_dao_related_transaction.rs, integration/src/tests/build_simple_transfer_transaction.rs, integration/src/tests/build_sudt_issue_transaction.rs, integration/src/tests/build_transfer_transaction_ckb.rs, integration/src/tests/build_transfer_transaction_ckb_pw.rs, integration/src/tests/build_transfer_transaction_udt.rs, integration/src/utils/address.rs, integration/src/utils/instruction.rs, tests/tests/rpc/build_dao_deposit_transaction.rs, tests/tests/rpc/build_simple_transfer_transaction.rs, tests/tests/rpc/build_sudt_issue_transaction.rs, tests/tests/rpc/build_transfer_transaction.rs
Rpc Type Breaking Change：
- replace Type Mode with Type OutputCapacityProvider for ckb/udt transfer.
- remove Type From, To
- update affected structs: TransferPayload，DaoDepositPayload，SudtIssuePayload
Fixes #
Ref #
=> refactor(rpc): replace Type Mode with Type OutputCapacityProvider

common/src/lib.rs, core/rpc/README.md, core/rpc/core/src/impl.rs, core/rpc/core/src/impl/build_tx.rs, core/rpc/core/src/impl/query.rs, core/rpc/core/src/impl/utils.rs, core/rpc/core/src/impl/utils_types.rs, core/rpc/core/src/lib.rs, core/rpc/core/src/tests/mod.rs, core/rpc/types/src/indexer.rs, core/rpc/types/src/lib.rs, integration/src/utils/signer.rs, tests/tests/rpc/build_dao_deposit_transaction.rs, tests/tests/rpc/build_transfer_transaction.rs, tests/tests/rpc/common.rs, tests/tests/rpc/get_balance.rs, tests/tests/rpc/get_transaction_info.rs, tests/tests/rpc/query_transactions.rs
* modify enum ScriptGroupType（LockScript/TypeScript -> Lock/Type）
* enum input parameters support snake name aliases
* break changes:
* ExtraType::CellBase -> ExtraType::Cellbase (correct spelling)
* ExtraFilter::CellBase -> ExtraFilter::Cellbase (correct spelling)
* ExtraFilter::Freeze -> ExtraFilter::Frozen (uniform naming)
* TransactionStatus::committed -> TransactionStatus::Committed（unified style：Capitalize the first letter of the output enume value）
Fixes #
Ref #
=> refactor(rpc): update rpc type and enum

core/rpc/README.md, core/rpc/core/src/error.rs, core/rpc/core/src/impl/adjust_account.rs, core/rpc/core/src/impl/build_tx.rs, core/rpc/core/src/impl/query.rs, core/rpc/core/src/impl/utils.rs, core/rpc/core/src/tests/utils_test.rs, core/rpc/types/src/lib.rs, integration/src/tests/build_adjust_account_transaction.rs, integration/src/tests/build_dao_related_transaction.rs, integration/src/tests/build_simple_transfer_transaction.rs, integration/src/tests/build_sudt_issue_transaction.rs, integration/src/tests/build_transfer_transaction_ckb.rs, integration/src/tests/build_transfer_transaction_udt.rs, integration/src/tests/get_balance.rs, integration/src/utils/instruction.rs, tests/tests/rpc/build_dao_withdraw_transaction.rs, tests/tests/rpc/build_sudt_issue_transaction.rs
Breaking Change：
- rpc Type `SudtIssuePayload` add `from` array filed, remove `pay_fee` filed
- rpc Type `DaoWithdrawPayload`  support `from` array input, remove `pay_fee` filed
- rpc Type `DaoClaimPayload` support `from` array input
- rpc `from` filed with Type `Vec<JsonItem>`, remove limit by `check_same_enum_value`
- rpc Type `AdjustAccountPayload` filed `from` modify Type from `HashSet<JsonItem>` to `Vec<JsonItem>` for unity
Maintenance:
- fix and udpate rpc readme doc
- removed the limitation that the number of accounts based on pw lock cannot be fully recycled
- the results of `get_balance` can be output in a certain order
Fixes #
Ref # …
=> refactor(rpc): update rpc type

core/storage/src/relational/fetch.rs, integration/README.md, integration/src/tests/build_dao_related_transaction.rs, integration/src/tests/build_simple_transfer_transaction.rs, integration/src/utils/instruction.rs
- Fixed a randomly failing integration test: `test_dao_by_out_point`
- description: Sometimes a failure occurs when running `test_dao_by_out_point`, in this test case, the withdrawing cells are from different transactions.
- reason: `get_transactions_with_status` returns the `input_cells` in the transaction but the order is not guaranteed to be in the order in the transaction. In this case, `build_dao_claim_transaction` relies on the assumption that the `input_cells` are in order to locate the deposit cells by withdrawing cells’ outpoint index.
- refactored integration test `test_simple_transfer_udt_from_provide_capacity`：avoid the possibility of affecting other tests.
Fixes #
Ref # …
=> fix(rpc):  transactions generated by rpc `build_dao_claim_transaction` will cause random `-14` dao script validation error
